
event = input ("Enter an event (ie. party, circus): ")
adj = input ("Enter an adjective (ie. scary, obscure): ")
color = input ("Enter a color (ie. blue): ")
object_name = input("Enter any object that can be held in one hand (ie. pin, watch): ")
shape_of_object = input ("Enter the general shape of the object you entered above: ")
animal = input ("Enter any animal (it can be mystical or realistic): ")
first_name = input ("Enter your first name: ")
emotion = input ("Enter a feeling (noun) (ie. sadness, anger): ")
adj2 = input ("Enter another adjective (ie. bustling, deadly): ")
adv = input ("Enter an adverb (ie. quickly, painfully (usually ends with -ly)): ")
adv2 = input ("Enter another adverb (ie. wickedly, slowly (usually ands with -ly)): ")




print("You had recieved an invitation to attend a(n)", event + ". The card was encased by an envelope that ")
print ("was a(n)", adj, color + "with arbitrary", shape_of_object, "stamp. ")
print("You’re friend was supposed to go with you, but as you were on your way to the", event + ", you get a ")
print("text from your friend saying that he would not be able to make it. ")
print("That was odd, as he is always there with you to make you feel safe. ")
print("So, you walk into the", event, "and immediately notice that everyone is wearing", animal, "masks. ")
print("There was nothing in the invitation about a(n)", animal, "mask dress code.")
print("Nervously you walk through the bustling crowd trying to see if anyone seems familiar")
print("to you, but the masks concealed too much of their faces. ")
print("Then you spot one other person not wearing a mask on her face. ")
print("She does not have a(n)", animal, "face on, which makes you a bit confused. ")
print("You start to follow her as")
print("she makes her way to a secluded area. As you get closer to her, you notice that she is holding a oddly familiar object. ")
print("As you get a closer look, you are shocked to see that it is a(n)", object_name, "that you have on your bedside table at home, ")
print ("but what really takes you")
print("by surprise is the carving on the object. The carving spells out your name,", first_name + ". ")
print("As you go to reach your hand out to tap her on the shoulder and ask about the object, ")
print("the crowd around you starts to move frantically, ")
print("pushing you away from the girl and eventually you cannot see her anymore through the heavy crowd. ")
print("You start to feel a sense of", emotion, "come over you and notice that there is door that opens to the balcony. ")
print("Trying to get away from the crowd of", animal + "s. ")
print("As you stand on the balcony, you go to look down at the", adj2, "city below, when you feel a tap on your shoulder. ")
print("Your heart starts to beat", adv + ", while you turn to face the girl from before backed by an army of", animal, "masks. ")
print('The girl leans in and whispers', adv2, 'into your ear, “It’s death day, Your Majesty."')
print("The last sight you see is all the", animal + "s closing in on you before you plummet through the air. ")
print("That is when you remember: the", animal, "was the symbol found on your kingdom's sigil. ")
